// A simulated cat with a KNOWN true expenditure — the ground truth the estimators can be scored
// against. Test-only (not imported by the app), but it lives in src/lib so the coverage tests and
// any future estimator can share one definition of "a realistic cat".
//
// WHY THIS EXISTS. Every estimator test until now used synthetic data shaped like the estimator's
// own assumptions, which can only prove the implementation matches the model — never that the model
// matches a cat. To catch misspecification you need data generated by a DIFFERENT process than the
// one being fitted, then to ask how often the reported interval actually contains the truth.
//
// THE THREE THINGS A REAL CAT'S SCALE READING CONTAINS, which earlier sims collapsed into one:
//
//   1. TRUE BODY MASS (W) — moves only via the energy balance, slowly. This is the signal.
//   2. GUT FILL (T) — food and water in transit, plus bladder/bowel. Genuine mass on the scale,
//      but carrying NO energy-balance information: it arrives and leaves without the cat gaining
//      or losing anything. Modelled as an AR(1) so it persists across a day or two rather than
//      being independent noise — which is what makes it dangerous, since a persistent wobble
//      mimics a real trend. This is what v3's transient state is for, and a simulation without it
//      silently never tests that state.
//
//      Expressed as a PERCENTAGE OF BODY MASS, not an absolute weight: gut content scales with the
//      animal, so a fixed 0.03 kg would be a rounding error on a human and a fifth of a cat's daily
//      food. PROVENANCE, stated plainly because it matters: I know of no feline study measuring
//      day-to-day weight variability. The default is borrowed from the human figure, where the
//      day-to-day SD is on the order of ~1% of body mass — which for a 4.95 kg cat is ~50 g,
//      roughly one day's wet-food intake, so it at least passes a sanity check. It is an ASSUMPTION,
//      not a measurement, which is why the tests SWEEP it (0.3%-2%) rather than trusting the point
//      value: a conclusion that only holds at one gut-fill level isn't a conclusion.
//   3. MEASUREMENT NOISE — the scale's own error, per reading, and it differs by an order of
//      magnitude between methods (0.01 kg pet scale, 0.03 Litter-Robot, 0.15 subtraction) and
//      between individual cats/units. Varying it across simulated cats is the point: a
//      conclusion that only holds at one noise level isn't a conclusion.
//
// EXPENDITURE MODELS. `allometric` is the physically motivated one: maintenance scales as W^0.75
// (the RER exponent), so losing weight LOWERS the burn, which shrinks the deficit, which slows the
// loss — a self-limiting loop no random walk reproduces. `randomWalk` is the drift the current
// filters assume. `constant` is the easy case. Being able to generate all three is what lets a
// test say "this estimator is well-calibrated under the drift cats actually have."

import { KCAL_PER_KG } from "./expenditure.js";

// Deterministic RNG — reproducible runs, so a coverage figure is a fact about the code and not
// about which random seed the CI happened to draw.
export function rng(seed = 12345) {
  let s = seed >>> 0 || 1;
  const next = () => (s = (s * 1103515245 + 12345) & 0x7fffffff) / 0x7fffffff;
  let spare = null;
  return {
    unit: next,
    // Box-Muller, cached — two normals per pair of uniforms.
    normal() {
      if (spare != null) { const v = spare; spare = null; return v; }
      let u = 0, v = 0;
      while (!u) u = next();
      while (!v) v = next();
      const r = Math.sqrt(-2 * Math.log(u));
      spare = r * Math.sin(2 * Math.PI * v);
      return r * Math.cos(2 * Math.PI * v);
    },
  };
}

const isoFrom = (dayIndex, epochMs = Date.UTC(2026, 0, 1)) =>
  new Date(epochMs + dayIndex * 86400000).toISOString().slice(0, 10);

export const SIM_DEFAULTS = {
  days: 56,
  W0: 4.95,           // kg, true body mass at the start
  E0: 250,            // kcal/day maintenance at W0
  deficit: 45,        // kcal/day fed BELOW E0 (negative = surplus)
  intakeSd: 12,       // day-to-day variation in what actually gets eaten
  readsPerDay: 3,
  sigmaW: 0.03,       // per-reading measurement noise, kg — a property of the SCALE, so absolute
  gutPct: 0.008,      // gut-fill innovation sd as a FRACTION of body mass (see the note above)
  gutPhi: 0.6,        // how much gut fill persists day to day (0 = white noise, →1 = a slow wander)
  method: "litterRobot",
  drift: "allometric", // "allometric" | "randomWalk" | "constant"
  driftSd: 0,         // extra random-walk drift on E (kcal/day per day), used by "randomWalk"
  seed: 12345,
};

// → { weightEntries, intakeEntries, truth: [{ date, E, W }], EtrueEnd, W0, Wend }
// weightEntries/intakeEntries are in the { date, value, method } shape the estimators consume.
export function simulateCat(opts = {}) {
  const P = { ...SIM_DEFAULTS, ...opts };
  const R = rng(P.seed);
  const k = P.E0 / Math.pow(P.W0, 0.75); // allometric constant, so E(W0) === E0

  let W = P.W0;          // TRUE body mass — only the energy balance moves this
  let T = 0;             // gut fill — rides on top of the scale reading, carries no energy signal
  let Ewalk = 0;         // accumulated random-walk component, when that model is selected
  const weightEntries = [], intakeEntries = [], truth = [];

  for (let d = 0; d < P.days; d++) {
    const date = isoFrom(d);
    const base = P.drift === "constant" ? P.E0 : k * Math.pow(W, 0.75);
    if (P.driftSd) Ewalk += R.normal() * P.driftSd;
    const E = (P.drift === "allometric" ? base : P.E0) + Ewalk;

    const intake = P.E0 - P.deficit + R.normal() * P.intakeSd;

    // Energy balance moves TRUE mass only. Gut fill is layered on the observation, never here —
    // that separation is the whole point: an estimator that mistakes gut fill for body mass will
    // read a trend that carries no calories.
    W += (intake - E) / KCAL_PER_KG;
    T = P.gutPhi * T + R.normal() * (P.gutPct * W); // scales with the animal, not a fixed kg

    for (let r = 0; r < P.readsPerDay; r++) {
      weightEntries.push({ date, value: W + T + R.normal() * P.sigmaW, method: P.method });
    }
    intakeEntries.push({ date, value: intake });
    truth.push({ date, E, W });
  }

  return {
    weightEntries, intakeEntries, truth,
    EtrueEnd: truth[truth.length - 1].E,
    W0: P.W0, Wend: W,
  };
}

// Score an estimator over many simulated cats.
// `estimate(weightEntries, intakeEntries)` must return { kcal, sd } like the real ones.
// → { coverage, bias, mae, halfWidth, n } — coverage is the headline: a 95% interval should
// contain the truth ~95% of the time. Well above that is an over-wide band (uselessly vague);
// below it is over-confidence (actively misleading).
export function scoreEstimator(estimate, { cases = 100, vary = {}, ...opts } = {}) {
  const signed = [], abs = [], widths = [];
  let hits = 0;
  for (let i = 0; i < cases; i++) {
    // Each case gets its own seed AND, where asked, its own noise level / gut behaviour — a
    // result that only holds for one kind of cat on one kind of scale isn't worth reporting.
    const varied = {};
    for (const [k2, [lo, hi]] of Object.entries(vary)) {
      varied[k2] = lo + ((i + 0.5) / cases) * (hi - lo);
    }
    const sim = simulateCat({ ...opts, ...varied, seed: 1000 + i * 7919 });
    const out = estimate(sim.weightEntries, sim.intakeEntries);
    if (out?.kcal == null || !(out.sd >= 0)) continue;
    const err = out.kcal - sim.EtrueEnd;
    const half = 1.96 * out.sd;
    if (Math.abs(err) <= half) hits++;
    signed.push(err); abs.push(Math.abs(err)); widths.push(half);
  }
  const mean = (a) => (a.length ? a.reduce((x, y) => x + y, 0) / a.length : NaN);
  return {
    n: abs.length,
    coverage: abs.length ? (hits / abs.length) * 100 : NaN,
    bias: mean(signed),   // >0 = reads high; with a losing cat that means lagging above the truth
    mae: mean(abs),
    halfWidth: mean(widths),
  };
}
